### ISSUE TITLE
`mypy-type-checker.ignorePatterns` doesn't work with glob pattern as documented

### ISSUE THREAD

**Issue by Mutantpenguin** [microsoft/vscode-mypy#213] opened 2023-11-07 13:35 UTC
### Problem
The documentation of `mypy-type-checker.ignorePatterns` states that it works with glob patterns like described in https://code.visualstudio.com/docs/editor/glob-patterns

But this is not true.

Your implementation uses `match` from `pathlib` that (as far as I understand it) doesn't work with glob patterns.

### Example
```python
import pathlib

def is_match(patterns: list[str], file_path: str) -> bool:
    """Returns true if the file matches one of the glob patterns."""
    if not patterns:
        return False
    return any(pathlib.Path(file_path).match(pattern) for pattern in patterns)

patterns: list[str] = [
    "**/a_path/**/*.py",
]

file_path: str = "/a_path/a_subpath/a_subpath/my_file.py"

print(is_match(patterns, file_path))
```

This prints out `False`.

Replacing `**/a_path/**/*.py` with `**/a_path/**/**/*.py` will return `True`.

### External Sources
Here you can see, that the glob pattern `**/a_path/**/*.py` should work:
* https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2Fa_path%2F%2A%2A%2F%2A.py&matches=false&tests=%2Fa_path%2Fa_subpath%2Fa_subpath%2Fmy_file.py

**Comment by tabbea** [comment] 2023-11-08 01:21
Hi, @karthiknadig amd @Mutantpenguin!

I see that my issue (#214) is a duplicate of this one.
Could you offer any suggestions of a working expression?

Even the full address `"/mnt/c/Users/bread/Documents/abz_code/graveyard/*.py"` doesn't seem to work.
Thanks again!

**Comment by karthiknadig** [comment] 2023-11-08 17:22
@tabbea In the report scope `workspace` case we are not applying the filtering. The filtering feature was added because linters do not exclude files even if there is a pattern match if the file path is explicitly used when linting.

**Closed** 2023-11-13 20:20 UTC
Labels: triage-needed
