### ISSUE TITLE
Blue underline not useful

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-mypy#252] opened 2024-01-02 22:07 UTC
When a function is called with incorrect arguments, the call is underlined in squiggly red (great) and the entire function contents get underlined in squiggly blue. The tooltip on the blue is useless: "<function> defined here". Well, duh, I have my pointer on it.

![image](https://github.com/microsoft/vscode-mypy/assets/26465923/53ea9b97-39f5-47d8-abfd-a84a15c6e9b0)

This means if I change a function signature, all that code turns blue until I got find all references to the function which use the old function.

Underlining potentially dozens of lines of code is not helpful. And the blue underlining of "this function is here"  - looks totally random when you see it. The tooltip for the bad call does not have a button to take you to the definition, and vice versa. I can always right click on the red underlined bad function call and say "Go to Definition"; the other way is not so easy. So I don't see how underlining a bunch of code because an error exists in who-knows-what-other-file is helpful.

**Comment by karthiknadig** [comment] 2024-01-02 22:12
@shaperilio We report whatever `mypy` reports as an issue. You can see Output > Mypy Type Checker for the result.

**Comment by karthiknadig** [comment] 2024-01-03 00:26
> Are you telling me mypy is telling you to underline entire functions in blue?

That is correct. Here is how mypy tells us:
![image](https://github.com/microsoft/vscode-mypy/assets/3840081/8c585ed7-1ec9-4383-aec3-9334c7173122)

It gives us the line and column number ranges to highlight.

**Comment by shaperilio** [comment] 2024-01-03 00:51
I see you have a play repo already set up. What does it show for my particular issue?

**Comment by karthiknadig** [comment] 2024-01-03 01:50
I don't have it set up for your particular issue. You should be able to see that in the logs. You can clear the logs before opening the file to see the results just for that file.

**Comment by karthiknadig** [comment] 2024-01-03 19:12
Duplicate of https://github.com/microsoft/vscode-mypy/issues/251

Considering this as duplicate since #251 is also about range of squiggles shown for a given issue.

**Closed by karthiknadig** 2024-01-03 19:12 UTC
Labels: triage-needed
