### ISSUE TITLE
showing errors that are already fixed

### ISSUE THREAD

**Issue by tombohub** [microsoft/vscode-mypy#25] opened 2023-04-23 22:30 UTC
It showed me error for a function arguments:

![image](https://user-images.githubusercontent.com/3029412/233869556-565c2efd-b793-462d-a8bb-e0bbb87c41f8.png)

which I fixed:

![image](https://user-images.githubusercontent.com/3029412/233869575-44f084cb-a33e-455b-b690-bd07f27c0f9b.png)

it's still there and it doesn't go away after window reload

**Comment by karthiknadig** [comment] 2023-06-09 22:11
Duplicate of https://github.com/microsoft/vscode-mypy/issues/22

The cause for both issues is the same

**Closed by karthiknadig** 2023-06-09 22:11 UTC
Labels: triage-needed
