### ISSUE TITLE
MyPy called with ambiguous option "--show-error-code"

### ISSUE THREAD

**Issue by GabrielDamsholt** [microsoft/vscode-mypy#155] opened 2023-09-19 11:50 UTC
When using the latest (non-bundled) MyPy version 1.5.1 the MyPy VSCode extension log throws the error `ambiguous option: --show-error-code could match --show-error-codes, --show-error-code-links`.

Why does the MyPy extension call MyPy with any arguments that I have not specified myself? Is this really necessary/desirable?

**Comment by karthiknadig** [comment] 2023-09-19 16:38
@GabrielDamsholt This is addressed in pre-release.

> Why does the MyPy extension call MyPy with any arguments that I have not specified myself? Is this really necessary/desirable?

If we don't pass these arguments there is no way to parse the output and match it to the exact line where the error is.

**Comment by karthiknadig** [comment] 2023-09-19 16:40
Duplicate of https://github.com/microsoft/vscode-mypy/issues/145

**Closed by karthiknadig** 2023-09-19 16:40 UTC
Labels: triage-needed
